apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation-producer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geolocation-producer
  template:
    metadata:
      labels:
        app: geolocation-producer
    spec:
      containers:
        - name: geolocation-producer
          image: 217100784311.dkr.ecr.ap-southeast-1.amazonaws.com/geolocation-repo:v1
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq-service"
---
apiVersion: v1
kind: Service
metadata:
  name: geolocation-producer-service
  namespace: default
spec:
  selector:
    app: geolocation-producer
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
