apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geolocation
  template:
    metadata:
      labels:
        app: geolocation
    spec:
      containers:
        - name: geolocation-container
          image: markesplana514/geolocation-service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: geolocation-service
  namespace: default
spec:
  selector:
    app: geolocation
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
