apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: ap-southeast-1

vpc:
  id: "vpc-0766e666d9f13c7f2" # Replace with vpc_id from terraform output
  subnets:
    public:
      public-1:
        id: "subnet-032a786897597e744" # Replace with public_subnet_1_id
      public-2:
        id: "subnet-05308a471825f21dd" # Replace with public_subnet_2_id
    private:
      private-1:
        id: "subnet-09fdc6f6c88517da7" # Replace with private_subnet_1_id
      private-2:
        id: "subnet-07c730389bf7e8203" # Replace with private_subnet_2_id

nodeGroups:
  - name: worker-nodes
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 3
    privateNetworking: true
    subnets:
      - private-1
      - private-2
