apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: ap-southeast-1

vpc:
  id: "vpc-06dfa89f1bdf9aab1" # Replace with vpc_id from terraform output
  subnets:
    public:
      public-1:
        id: "subnet-0d7a81b6c6b2b2fa9" # Replace with public_subnet_1_id
      public-2:
        id: "subnet-051db9cedb784881e" # Replace with public_subnet_2_id
    private:
      private-1:
        id: "subnet-03237422c8c37ada8" # Replace with private_subnet_1_id
      private-2:
        id: "subnet-00c3a04fdd931e387" # Replace with private_subnet_2_id

nodeGroups:
  - name: worker-nodes
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 3
    privateNetworking: true
    subnets:
      - private-1
      - private-2
