apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: ap-southeast-1

vpc:
  id: "vpc-0ccba8dac2a9b4c00" # Replace with vpc_id from terraform output
  subnets:
    public:
      public-1:
        id: "subnet-00fc1e279ed856a42" # Replace with public_subnet_1_id
      public-2:
        id: "subnet-063eba392c56decaf" # Replace with public_subnet_2_id
    private:
      private-1:
        id: "subnet-08e7b5a25073bcec5" # Replace with private_subnet_1_id
      private-2:
        id: "subnet-0bb50e52f07dc01fc" # Replace with private_subnet_2_id

nodeGroups:
  - name: worker-nodes
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 3
    privateNetworking: true
    subnets:
      - private-1
      - private-2
